title: NSF CICI PI Meeting
description: >-
  The CICI PI Meeting brings together Principal Investigators funded through the
  National Science Foundation's Cybersecurity Innovation for Cyberinfrastructure
  (CICI) program to share research progress, exchange best practices, and
  strengthen collaboration.
preposition: "at"
baseurl: ""
url: ""

remote_theme: "DigitaleGesellschaft/jekyll-theme-conference@v3.7.2"

conference:
  # Information modals (shown as modal dialogs)
  # info_modals:
  #   - title: Important Announcement
  #     main_only: true
  #     text: This is an information modal that appears as a dialog.

  # Information bars (shown as alerts at the top of the page)
  info_bars:
    - title: Registration Open!
      color: primary
      text: |
        <ins>[Registration (due April 24th) and poster submission (due May 1st) is now open!](/registration)</ins>

      # - title: Important Notice
      #   color: warning
      #   text: |
      #     This is a non-dismissible information banner that will always be visible.
  lang: en
  tz: "-07:00"
  program:
    url: /program/
    time_steps: 30
    show_alltimes: true
  location:
    url: /location/
  navigation:
    links:
      - name: Home
        relative_url: /
      - name: Program
        relative_url: /program/
      # - name: Events
      #   relative_url: /talks/
      # - name: Speakers
      #   relative_url: /speakers/
      - name: Attendee Information
        menu:
          - name: Participant Guide
            relative_url: /attend/guide
          - name: Venue
            relative_url: /attend/venue
          - name: Travel
            relative_url: /attend/travel
      - name: Registration
        relative_url: /registration/
      # - name: Organizers
      #   relative_url: /organizers/
  talks:
    tracks:
      - name: Logistics
        color: secondary
      - name: Plenary
        color: danger
      - name: Poster Session
        color: info
      - name: Breakout
        color: success
      - name: Panel
        color: warning
  meta:
    schema_org:
      disable: false
      event_status: scheduled
      event_attendance_mode: offline
      has_participation_offer:
        url: /registration/

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room
